[project]
name = "hello-meshtastic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "meshtastic>=2.6.4",
    "mudp>=1.0.0a4",
    "paho-mqtt>=2.1.0",
]
